### ISSUE TITLE
add mixed array to (de)serialization

### ISSUE THREAD

**Issue by ghost** [markusdiewald/oom#2]

**Comment by ghost** [comment]
// 3. serialize all items
            // ... include type, so we can deserialize sub-classes to interface type
            var settings = new JsonSerializerSettings() { Formatting = Formatting.Indented, TypeNameHandling = TypeNameHandling.Auto };
            Console.WriteLine(JsonConvert.SerializeObject(items, settings));

**Comment by markusdiewald** [comment]
Added mixed array again to Program.cs and (de)serialized it accordingly
